# Intro to ML 

* using Introduction to statistical learning by Gareth James as a companion book 

* free online

* Mathmatical theroy from said book will be applied and read

* What is ML? 

* method of data analysis that automates analytical model building. 

* using algorithms that iteratively learn from data, ML allows computers to find hidden insights without being explicitly programmed where to look.

* used for but not limited to: 
    * Fraud detection, web search results, real time ads on webpages, credit scoring and next best offers, prediction of equipment failures, new pricing models, network intrusion detection, recommendation engines, customer segmentation, text, sentiment analysis, predicting  customer churn, pattern and imgage recognition, email spam filtering, financial modeling and more. 
    
### ML process: 

 * Data aquisition 
 * data cleaning
 * model training&building/ test data, model testing, repeat as many times as necessary.
 * model deployment
 
#### Threee types of ML Algorithms:
* Supervised learning
* unsupervised Learning
* Reinforcement Learning


##### Supervised Learning
* you have labeled data and are trying to group together similar data points based off of features 

##### Unsupervised Learning
* You have unlabeled data and are trying to group together similar points based off of features 

##### Reinforcement Learning
* Algorithm learns to perform an action from experience.


------------------------------------------------------------------
##### Supervised Learning
* supervised Learning algorithms are trained using Labeled examples such as an imput where the desired output is known.

* For example a piece of equipment could have data points labeled either 'F' (failed) or 'R' (runs).

* The Learning algorithm recieves a set of inputs along with the corresponding correct outputs and the algorithm learns by comparing its actual output with correct outputs to find errors.

* it then modifies the model accordingly. 


* through methods like classification regression prediction and graidient boosting supervisied learning uses patterns to predict the values of the label on addtional unlabeled data.

* supervised learning is commonly used in applications where historical predicts likely future events. 

* example can anticipate when credit card fraud transactions are likely to be fraudulent or when insurance customer is likely to file a claim.

* Or it can attempt to predict the price of a house based on different features for houses for which we have historical price data. 
----------------------------------------------------------------------
##### Unsupervised Learning

* is used against data that has no historical labels 

* not told the 'right answer'. algorithm must figure out on it's own 

* goal is to explore the data and find some structure within. 

* can find the main attributes that spearate customer segments from each other.

* popular techniques include self-organizing maps, nearest-neighbor mapping, k-means clustering and singular value decomposition.

* these algorithms are also used to segment text topics, recommend items and identify data outliers.
------------------------------------------------------------------------
##### Reinforcement Learning
* often used for robotics gaming and navigation. 
* with reinforcement learning , the algorithm discovers through trial and error which actions yiled the greatest rewards. 
* this type of learning has three primary components the agent (learner or decision maker), enviorment  (everything it interacts with) and actions (what the agent can do)

* objective for the agent to choose actions that maximize the expected reward over a given amount of time. 

* agent will reach the goal much faster by following a good policy.

* the goal is to learn the best policy.

----------------------------------------------------------------------

* for each algorithm or ML topic:
    * reading assignment
    * light overview of theory
    * Domonstration Lecture with Python
    * ML project assignment
    * overview solution of said project.


#  ML with Python

* we will be using SciKit Learn package

* Most popular ML package for python and has a lo of algorithms built-in. 

* install with conda install scikit-learn or pip install scikit-learn

* basic structure of how to use scikt learn
* but first quick review of ML process (...again):
     * Data aquisition 
     * data cleaning
     * model training&building/ test data, model testing, repeat as many times as necessary.
     * model deployment
     
* Going over an example of the process to use SciKit Learn

every algorithm in scikit-learn via an "Estimator" First you'll import the model, general form is:


In [1]:
# from sklearn.family import Model
# for example:
import sklearn
from sklearn.linear_model import LinearRegression 

 * Estimator paramaters: all the params of an estimate can be set when it is instantiated, and have suitable default values.
 
 * you can use shift+tab in jupyter to check possible params. 
 
 example:

In [2]:
model = LinearRegression(normalize= True)
print(model)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)


Once you have your model created with your parameters, it is time to fit your model on some data! 

But remember, we should split this data into a training set and a test set. 

In [3]:
import numpy as np 

In [7]:
from sklearn.model_selection import train_test_split
X,y = np.arange(10).reshape((5,2)),range(5)
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [8]:
list(y)

[0, 1, 2, 3, 4]

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [10]:
X_train

array([[0, 1],
       [8, 9],
       [6, 7]])

In [11]:
y_train

[0, 4, 3]

In [12]:
X_test

array([[4, 5],
       [2, 3]])

In [13]:
y_test

[2, 1]

now that we have splt the data we can train/fit our model on the training data. 

this is done through the model.fit() method:

In [14]:
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

* Now the model has been fit and trained on the training data.
* The model is ready to predict labels our label or values on the test set! 
We get the predicted values using the predict method:

In [15]:
predictions = model.predict(X_test)

We can then evaluate our model by comparing our predictions to the correct values.

the evaluation method depends on what sort of ML algorithm we are using (Regression, Classification, Clustering, etc.)

Let's get a quick recap!

Scikit-learn strives to have a uniform interface across all method and we'll see examples of these bellow.

given a sciit-learn estimator object named model the following methods are availible. . .

* Availible in ALL ESTIMATORS:
    * model.fit() : fit training data.
    * for supervised learning applications, this accepts two arguments: the data X and the labels y (e.g. mdeol.fit(X,y)).
    * For unsupervised learning applications, this accepts only a single argument, the data X (e.g.model.fit(X)).
    
* Availible in supervised estimators:
    * model.predict(): given a trained model, predict the label of a new set of data. this method accepts one arg, the new data X_new (e.g. model.predict(X_new)), and returns the learned label for each object in the array.
    * model.predict_proba():For classification problems,some estimators also provde this method, which returns the probability that a new observation has each categorical label. in this case, the label with the highest probability is returned by model.predict(). 
    * model.score() : for classification or regression problems, most estimators implement a score method. Scores are between 0 and 1, with a larger score indicating a better fit. 
    
* availible in unsupervised estimators
    * model.predict() : predict labels in clustering algorithms. 
    * model.transform(): given an unsupervised model, transform new data into the new basis. This also accepts one argument X_new, and returns new representation of the data based on the unsupervised model. 
    * model.fit_transform() : some estimators implement this method, which more effectively performs a fit and transform on the same input data. 
    
* How to choose and Algorithm 
    * Google scikit-learn algorithm cheat sheet. 

# Notation and simple matrix algebra

Chosing notation is always a difficult task we'll adopt the same notational conventions of ESL. 

N represesent the number of distinct data points or or observations in sample.

We will let P denote # of variables that are availible for use in making predictions. 

Example wage data set consists of 12 variables for 3000 people. N= 3000 observations and p=12 variables 

p might be quite large.

we will let xij represent the value of the jth variabl for the Ith observation where i=1,2...,p. "i" will be used to index samples or observations (from 1 to n) and j will be used to index the variables (from 1to p). We let x denote a n*p matrix whose (i,j)th element is Xij. (page 10)  
think of x as a spread sheat with n rows p cols

rows of x = x1,x2,x3,...xn. 

i = rows 
n = # of rows

j = cols 

p = # of cols

y hat equals f hat times x. f hat represents the resulting prediction of y. F hat is often treated like a black box in the sense that one is not typically concerned with the exact form of f hat provided that it yields accurate predictions for Y. 

Accuracy of y hat as a prediction for y depends on two quantities.  reducible error and irreducable error. f hat will not be a perfect estimation for f, this will introduce some error. it is reducable because we can potentially improve f hats accuracy by using the most appropriate statistical learning technique to estimate f. Even if we had a perfect estimate, our predictions would still ahve some error in it. this is because Y is also a function of random error. therefore no matter how well we estimate f we cannot reduce the error by the random error varibale. this is the irreducable error. 

irreducable error is larger than 0 quantity mantain unmeasured variables that useful in predicting Y since we dont measure them f cannot use them for its prediction the quanityt error may also contain unmeasureable variation. 


## Supervised Learning Problem

Starting point:
    * Outcome measurement Y (also called dependent variable, response, target).
    * vectorof p predictor measurement X (also called inputs, regressors, covaiates, features, independent variables).
    * In the regression problem, Y is quantitive (e. price, blood pressure)
    * in the classification problem, Y takes values in a finite, unordered set ( survived/ died, digit )-9, cancer class of tissue sample).
    *  We have training data (x1,y1),....,(xn,yn). These are observations (examples, instances) of these measurements. 

on the basis of the traning data we would like to:
* accurately predict unseen test cases
* Understan which inputs affect the outcome, and how.
* access the quality of our predictions and inferences.


# Philosophy 

* it is important to understand the ideas behind the various techniques, in order to know how and when to use them.

* one has to understand the simpler methods first in order to grasp the more sophisticated ones. 

* it is important to accurately assess the performance of a method, to know how well or how badly it is working. (simple often works as well as fancy does.)

* this is an exciting reseearch area, having important applications in science, industry and finance. 

* statistical learning is a fundumental ingredient in the training of a modern data scientist. 

### Unsupervised learning

* No outcome variable, jsut predictos measured on set of samples.

* objective is more fuzzy- find groups of sample that behave similarly, find features that behave similarly, find linear combinations of features with the most variation. 

* difficult to know how well you are doing. 

* different from supervised learning, but can be usefula s a pre-processing step for supervised learning. 


#### The netflix prize

* competition started in 2006, oct. training data is rating for 18k movies by 400k customers rating between 1 to 5.

* Sparse training data - 98% missing.

* objective to predicti the rating for a set of 1 million customer-movie pairs that are missing in training data. 

* original algorithm achieved a root MSE of 0.953. First team to achieve a 10% imporvement wins 